import React from 'react';

interface DashboardProps {
  className?: string;
}

/**
 * Dashboard Component
 * Auto-generated by Cline CLI automation
 */
export default function Dashboard({ className = '' }: DashboardProps) {
  return (
    <div className={`p-6 rounded-lg border ${className}`}>
      <h2 className="text-2xl font-bold mb-4">Dashboard</h2>
      <p className="text-gray-600">Component content goes here</p>
    </div>
  );
}
