import React from 'react';

interface DashboardCardProps {
  className?: string;
}

/**
 * DashboardCard Component
 * Auto-generated by Cline CLI automation
 */
export default function DashboardCard({ className = '' }: DashboardCardProps) {
  return (
    <div className={`p-6 rounded-lg border ${className}`}>
      <h2 className="text-2xl font-bold mb-4">DashboardCard</h2>
      <p className="text-gray-600">Component content goes here</p>
    </div>
  );
}
